FROM python:3.7

COPY docker/requirements.txt .

#folder inside copy
COPY /Django /CapD/Django
COPY secrets.json /CapD

RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx
RUN pip install -U -r requirements.txt

WORKDIR /CapD/Django/CapD_api

CMD [ "python","manage.py","runserver","0.0.0.0:8000" ]

EXPOSE 8000