FROM python:3.7

COPY docker/requirements.txt .
COPY /Django .

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install libgl1-mesa-glx
RUN pip install -U -r requirements.txt

WORKDIR /Django/CapD_api

CMD [ "python","manage.py","runserver","0.0.0.0:8000" ]

EXPOSE 8000