# Generated by Django 3.0.14 on 2021-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0005_auto_20210524_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='test1', max_length=200),
        ),
    ]
