# Generated by Django 3.0.14 on 2021-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0006_auto_20210524_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
