# Generated by Django 3.0.14 on 2021-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0008_auto_20210525_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='CapD_rest/app/one_cap/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='media/default.png', upload_to='CapD_rest/app/source'),
        ),
    ]
