# Generated by Django 3.0.14 on 2021-05-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0009_auto_20210528_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.TextField(),
        ),
    ]
