# Generated by Django 3.0.14 on 2021-05-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0010_auto_20210528_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='img_url',
        ),
    ]
