# Generated by Django 3.0.14 on 2021-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapD_rest', '0012_selected_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_person',
            name='selected_list',
            field=models.TextField(default='-1'),
        ),
    ]
